name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cabal: ["3.6"]
        ghc:
          - "8.8.4"
          - "8.10.7"

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Build
      run: |
        cabal update
        cabal build --enable-tests --enable-benchmarks

    - name: Test
      run: |
        cabal test --enable-tests
